name: density_k_10
task: density

data:
  n_samples: 50000
  scale: true
  random_state: 0

model:
  n_components: 10
  covariance_type: diag
  n_init: 2
  init_params: kmeans
  max_iter: 150
  random_state: 0
